version: '3'
services:
  nodejs:
    image: bank-app
    build: .
    depends_on:
      - mongodb
  mongodb:
    image: mongo:7.0
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
      - type: bind
        source: ./db-data/
        target: /data/db